# Generated by Django 4.2.11 on 2024-03-29 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('user_id', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('passport', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Oylik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jami_oylik', models.FloatField()),
                ('karobka_puli', models.FloatField()),
                ('bonus', models.FloatField()),
                ('avans', models.FloatField()),
                ('shtraf', models.FloatField()),
                ('ishlamagan_kun', models.FloatField()),
                ('forma', models.FloatField()),
                ('korpa_tushak', models.FloatField()),
                ('qushimcha', models.FloatField()),
                ('berildi', models.FloatField()),
                ('sana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='albinoUser.sana')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='albinoUser.telegramuser')),
            ],
        ),
    ]
