# Generated by Django 4.2.11 on 2024-04-03 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albinoUser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='status',
            field=models.CharField(blank=True, choices=[('aktiv', 'aktiv'), ('no_aktiv', 'No_aktiv')], default='no_aktiv', max_length=20, null=True),
        ),
    ]
