# Generated by Django 4.2.11 on 2024-04-03 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('albinoUser', '0002_telegramuser_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oylik',
            name='sana',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='albinoUser.sana'),
        ),
        migrations.AlterField(
            model_name='oylik',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='albinoUser.telegramuser'),
        ),
    ]
