# Generated by Django 4.2.11 on 2024-04-03 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('albinoUser', '0003_alter_oylik_sana_alter_oylik_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oylik',
            name='sana',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='albinoUser.sana'),
        ),
    ]
