# Generated by Django 4.2.11 on 2024-05-04 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albinoUser', '0004_alter_oylik_sana'),
    ]

    operations = [
        migrations.AddField(
            model_name='oylik',
            name='avans_plastik',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='oylik',
            name='kpi',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='oylik',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
